name: 'Semantic release pack'
description: 'Generates file and runs new release.'

inputs:
  author:
    required: true
    description: ""
  email:
    required: true
    description: ""
  token:
    required: true
    description: ""
  writeSummary:
    required: false
    default: "false"
    description: ""
  installNode:
    required: false
    default: "true"
    description: ""
  defaultBranch:
    required: true
    default: master
    description: ""
  nodejs:
    required: false
    default: '20'
    description: "Nodejs version"
  files:
    required: false
    default: "[]"
    description: ""
  npmPlugin:
    required: false
    default: "false"
    description: ""
  createRelease:
    required: false
    default: "true"
    description: ""
  updateChangelog:
    required: false
    default: "true"
    description: ""

runs:
  using: "composite"

  steps:
    - shell: bash
      if: inputs.writeSummary
      run: |
        echo "### 📦 Package" >> $GITHUB_STEP_SUMMARY

    - name: Check if .releaserc.json exists
      id: file_checker
      shell: bash
      run: |
        HAS_RELEASERC_FILE=$(if test -f .releaserc.json; then (echo "true"); else (echo "false") ; fi)
        echo "has_releaserc_file=$HAS_RELEASERC_FILE" >> $GITHUB_OUTPUT
        echo has_releaserc_file=$HAS_RELEASERC_FILE

    - name: Create .releaserc.json
      uses: filipeforattini/ff-iac-github-actions/.github/actions/create-releaserc-file@main
      if: steps.file_checker.outputs.has_releaserc_file == 'false'
      with:
        writeSummary: ${{ inputs.writeSummary }}
        defaultBranch: ${{ inputs.defaultBranch }}
        files: ${{ inputs.files }}
        npmPlugin: ${{ inputs.npmPlugin }}
        createRelease: ${{ inputs.createRelease }}
        updateChangelog: ${{ inputs.updateChangelog }}

    - name: Setup | NodeJs ${{ inputs.nodejs }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodejs }}

    - name: Setup | NodeJs NPM & yarn & pnpm
      if: inputs.nodejs != 'false'
      shell: bash
      id: npm
      run: npm -g install npm yarn pnpm && npm -v && yarn -v && pnpm -v

    - name: Semantic Release
      uses: filipeforattini/ff-iac-github-actions/.github/actions/semantic-release@main
      env:
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_AUTHOR_NAME: ${{ inputs.author }}
        GIT_AUTHOR_EMAIL: ${{ inputs.email }}
        GIT_COMMITTER_NAME: ${{ inputs.author }}
        GIT_COMMITTER_EMAIL	: ${{ inputs.email }}
