name: _self

on: 
  push:
  deployment:
  release:
    types: [created]
  pull_request:
    types: [opened, reopened]

jobs:

  IAC:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/iac.yml@main
    secrets: inherit
    with:
      mainBranch: main
